"use client";

import { useState } from "react";
import { BookCopy, Check, ChevronRight, LibraryBig, Plus, Share2 } from "lucide-react";
import { Dialog } from "../dialog";
import { SectionHeader } from "../section-header";
import { directStudents, person } from "@/modules/cetele/selectors";
import { useCetele } from "@/modules/cetele/store";

export function LibraryScreen() {
  const { state, dispatch } = useCetele();
  const [tab, setTab] = useState<"mine" | "shared" | "assignments">("mine");
  const [assignId, setAssignId] = useState<string | null>(null);
  const [createOpen, setCreateOpen] = useState(false);
  const [targets, setTargets] = useState<Record<string, number>>({});
  const definitions = state.definitions.filter((item) => tab === "mine" ? item.authorId === state.currentUserId : tab === "shared" ? item.visibility === "shared" && item.authorId !== state.currentUserId : true);
  const direct = directStudents(state).filter((student) => student.invitation === "active");
  const canAuthor = direct.length > 0;
  return <div className="workspace"><SectionHeader title="Alışkanlıklar" description="Anlamı mentor belirler; görünümü öğrenci kendine göre düzenler." actions={canAuthor ? <button className="primary-button" onClick={() => setCreateOpen(true)}><Plus size={18} /> Yeni alışkanlık</button> : undefined} />
    <div className="range-tabs library-tabs" role="tablist" aria-label="Alışkanlık bölümü"><button role="tab" aria-selected={tab === "mine"} className={tab === "mine" ? "active" : ""} onClick={() => setTab("mine")}>Benim alışkanlıklarım</button><button role="tab" aria-selected={tab === "shared"} className={tab === "shared" ? "active" : ""} onClick={() => setTab("shared")}>Paylaşılanlar</button><button role="tab" aria-selected={tab === "assignments"} className={tab === "assignments" ? "active" : ""} onClick={() => setTab("assignments")}>Atamalar</button></div>
    {tab === "assignments" ? <section className="assignment-ledger">{state.assignments.filter((item) => item.assignedBy === state.currentUserId).map((assignment) => <article key={assignment.id}><span className="mini-accent" style={{ background: assignment.accent }} /><div><h2>{state.definitions.find((item) => item.id === assignment.definitionId)?.name}</h2><p>{person(state, assignment.studentId)?.name} · {assignment.target ? `Hedef ${assignment.target}` : "İkili kayıt"}</p></div><span className="status-text calm"><Check size={15} /> {assignment.status === "active" ? "Atandı" : "Sona erdi"}</span></article>)}</section> : <section className="library-grid">{definitions.map((habit) => <article className="definition-card" key={habit.id}><div className="definition-icon"><LibraryBig size={22} /></div><div className="definition-copy"><span className="definition-meta">{habit.mode === "quantitative" ? `Nicel · Varsayılan ${habit.defaultTarget}` : "İkili"}{habit.visibility === "shared" ? " · Paylaşılan" : " · Özel"}</span><h2>{habit.name}</h2><p>{habit.description}</p><details><summary>Alışkanlık Rehberi <ChevronRight size={16} /></summary><div><strong>Neden önemli?</strong><p>{habit.why}</p><strong>Ne tamamlanmış sayılır?</strong><p>{habit.completionDefinition}</p><strong>Pratik öneri</strong><p>{habit.tips}</p></div></details>{habit.sourceAuthor || habit.visibility === "shared" ? <small><Share2 size={14} /> Kaynak: {habit.sourceAuthor ?? habit.creatorName}</small> : null}</div>{canAuthor ? <div className="definition-actions">{habit.authorId !== state.currentUserId ? <button className="secondary-button" onClick={() => dispatch({ type: "adopt", definitionId: habit.id })}><BookCopy size={17} /> Benimkine kopyala</button> : <button className="primary-button" onClick={() => setAssignId(habit.id)}>Öğrenciye ata</button>}</div> : null}</article>)}</section>}
    {createOpen ? <Dialog title="Yeni alışkanlık" onClose={() => setCreateOpen(false)}><form className="form-stack" onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); const mode = data.get("mode") === "quantitative" ? "quantitative" : "binary"; dispatch({ type: "create-definition", definition: { id: crypto.randomUUID(), authorId: state.currentUserId, name: String(data.get("name")), description: String(data.get("description")), guide: String(data.get("guide")), why: String(data.get("why")), completionDefinition: String(data.get("completionDefinition")), tips: String(data.get("tips")), mode, defaultTarget: mode === "quantitative" ? Number(data.get("target")) : null, visibility: data.get("visibility") === "shared" ? "shared" : "private" } }); setCreateOpen(false); }}><label>Ad<input name="name" required maxLength={100} /></label><label>Kısa açıklama<input name="description" maxLength={240} /></label><label>Alışkanlık Rehberi<textarea name="guide" rows={4} /></label><label>Neden önemli?<textarea name="why" rows={2} /></label><label>Ne tamamlanmış sayılır?<textarea name="completionDefinition" rows={2} required /></label><label>Pratik öneri<textarea name="tips" rows={2} /></label><label>Kayıt türü<select name="mode" defaultValue="binary"><option value="binary">İkili</option><option value="quantitative">Nicel</option></select></label><label>Varsayılan hedef<input name="target" type="number" min="1" step="1" defaultValue="10" /></label><label>Görünürlük<select name="visibility" defaultValue="private"><option value="private">Özel</option><option value="shared">Aynı ağa paylaşılan</option></select></label><button className="primary-button">Alışkanlığı kaydet</button></form></Dialog> : null}
    {assignId ? <Dialog title="Alışkanlık ata" onClose={() => setAssignId(null)}><div className="form-stack"><p>Atama yalnızca Doğrudan Öğrencinin kişisel Mülahazasında görünür.</p><section aria-labelledby="direct-assignment-heading"><h3 id="direct-assignment-heading">Doğrudan öğrenciler</h3><div className="student-choice-list">{direct.map((student) => <div className="student-target" key={student.id}><span className="avatar small">{student.initials}</span><span><strong>{student.name}</strong><small>Doğrudan öğrenci</small></span><label><span className="sr-only">{student.name} hedefi</span><input type="number" min="1" step="1" value={targets[student.id] ?? state.definitions.find((item) => item.id === assignId)?.defaultTarget ?? 1} onChange={(event) => setTargets((current) => ({ ...current, [student.id]: Number(event.target.value) }))} /></label><button className="icon-button" aria-label={`${student.name} için ata`} onClick={() => { dispatch({ type: "assign", definitionId: assignId, studentId: student.id, target: targets[student.id] ?? state.definitions.find((item) => item.id === assignId)?.defaultTarget ?? null }); setAssignId(null); }}><ChevronRight size={18} /></button></div>)}</div></section></div></Dialog> : null}
  </div>;
}
